### PR TITLE
Migrate visual components to Vue.js

### LINKED ISSUE #29: Adopt a frontend framework
We've gotten pretty far with plain JavaScript, but there's no good reason not to use a modern UI framework like Vue, especially now that we have a build process in place. We should see how much cleaner the src/js/visual/ modules can be if we can define them as UI components.

### PR DESCRIPTION
**Pull request by steinbro**
Work in progress. Once complete, closes #29.

### CODE REVIEW

**Comment by sebastianovide** [comment]
Have you already made up your mind about Vue? I personally like Vue more than React. Nevertheless, I would choose React because it is so popular and has many robust, solid libraries. Actually, I would use React Native, as it will give you both a PWA and a native app at the same time. This way, we can get rid of Capacitor, which I'm currently using as a quick workaround for converting an existing app into a native app. Just my 2 cents.

**Comment by steinbro** [comment]
Yeah, I've started down the Vue path in part because it seemed easier to migrate an existing project, replacing components one at a time. I also was looking for an excuse to practice Vue specifically, for reasons unrelated to this project.

**Comment by sebastianovide** [comment]
> Yeah, I've started down the Vue path in part because it seemed easier to migrate an existing project, replacing components one at a time. I also was looking for an excuse to practice Vue specifically, for reasons unrelated to this project.

Yeah, Vue seems simpler. OK, forget about the idea of killing two birds with one stone. Capacitor + Vue should do the trick.

**Comment by steinbro** [comment]
OK, I've managed to replace all the UI-related JS files with Vue components. I suspect there's lots of room to improve style and clean things up, but this PR is already big enough.

**Comment by sebastianovide** [comment]
looking good 🥇

**Pull request merged**
