### PR TITLE
fixed voices not being populated in web

### PR DESCRIPTION
**Pull request by sebastianovide**
and missing the default

### CODE REVIEW

**Comment by steinbro** [comment]
I can reproduce the regression (voice list is empty on first load) on Firefox + Windows, but this patch doesn't seem to fix it. The voice list is populated if I simply refresh the page, but if I quit and restart the browser, it's empty again.

**Comment by sebastianovide** [comment]
very odd.... in fact that was a hack more than a fix after different trials an errors....  I've opened a ticket in https://github.com/capacitor-community/text-to-speech/issues/130

**Comment by steinbro** [comment]
I think I fixed it in 84fa8fa on main. Does it work for you?

In the process of the Vue conversion, I inadvertently dropped the `window.speechSynthesis.onvoiceschanged` event binding. I take it that at least in some browsers there's some delay between page load and TTS being available, so attempting to load voices may only succeed after that event is first triggered.

**Comment by sebastianovide** [comment]
o yep... it works :clap:

**Pull request closed without merging**
