### PR TITLE
FAQ Page

### PR DESCRIPTION
**Pull request by jonha1**
draft of the new FAQ page

 closes issue#[16](https://github.com/soundscape-community/soundscape-web-client/issues/16)

### CODE REVIEW

**Comment by steinbro** [comment]
Thanks for your work on this! A few items:

1. The question mark button falls off the side of the screen, at least when I use the mobile display simulator in desktop Firefox:
Screen Shot 2024-04-13 at 22 04 09
I'm sure there's better use of screen real estate, like a second row of buttons, but perhaps that should be a separate pull request. For now, just make sure the button is actually visible without horizontal scrolling.
2. The home button isn't rendering with the expected width:
Screen Shot 2024-04-13 at 22 04 54
3. The diff for the PR shows reversions of some upstream changes. I'm sure this was unintentional, but make sure your branch accurately reflects only the relevant changes. Since I think this same branch was already merged earlier, it might be cleanest to fork a new branch off of `main` and apply your changes onto that.

**Comment by jonha1** [comment]
Thank you for the feedback. I finished the changes you requested in 1 and 2 earlier. I also plan to investigate how the page looks on safari.

For #3 about the upstream changes, I wanna clarify if it would be easier if you are  suggesting if I should make a new branch from main and put all the changes I have done onto the new branch I just created.

@steinbro

**Comment by steinbro** [comment]
Great, thanks! I can confirm the ? button now fits on the screen, but the buttons now have no visible space between them. This isn't great for accessibility, since users who can't make out the button labels may navigate based on the nth button on the screen, which is tough to distinguish now. I'd suggest making the voice drop down narrower; it's currently just showing the first few characters of the voice name, which isn't super helpful (especially on Windows, where all the voice names star with "Microsoft").

As for the upstream changes, yes, I was suggesting one possible fix that would save you some git merging headaches is to just start a new branch . This needs to be fixed because, for example, the redesigned speed controller no longer works because the changes in app/js/visual/voicecontrols.js have been inadvertently reverted in this branch.

**Comment by jonha1** [comment]
I'll work on those as soon as possible. 

If future developers would like to know how soundscape would look on Safari on other IOS devices, should I include documentation? If so, where would you like me to include documentation on this?

Below are screenshots on how soundscape looks on an iPhone 8. Im not sure if we can see if there are more updated options for choosing an iPhone but I will look into it and provide feedback.
Screen Shot 2024-04-21 at 11 35 05 PM

Screen Shot 2024-04-21 at 11 36 36 PM

In the first image, the Google voices don't appear in the voice dropdown.

**Comment by steinbro** [comment]
Eh, no need to document how the app renders in the Safari mobile rendering mode. Ideally, these images will quickly become out-of-date anyway.

**Comment by jonha1** [comment]
I just fixed the spacing in the header, let me know if it's good. If no other changes are needed, then I will make a new branch and merge those changes.

**Comment by steinbro** [comment]
Looks and sounds good!

**Comment by jonha1** [comment]
I tested my branch and it should be ready for a merge.

**Comment by steinbro** [comment]
It needed a good bit more cleanup, but it's finally ready for merge :)

**Pull request merged**
