### PR TITLE
Reorganize folder structure to match Vue idioms

### PR DESCRIPTION
**Pull request by steinbro**
- Move icons + sounds out of src into assets
- Move App.vue, main.css directly under src
- Reorganize JS files into store, utils directly under src

@sebastianovide did I break anything in the PWA/Android app?

### CODE REVIEW

**Comment by sebastianovide** [comment]
> did I break anything in the PWA/Android app?

yep. something happened to the heading: `TypeError: myLocation.sstHeading is not a function`

**Comment by steinbro** [comment]
Grr, typo. How about now? Maybe next I'll convert to TypeScript to catch those at compile time :)

**Comment by sebastianovide** [comment]
yep, +1 for TypeScript ....

I don't see the errors any more but I cannot see the  arrow neither...

**Comment by steinbro** [comment]
> I don't see the errors any more but I cannot see the arrow neither...

Yeah, noticed that too, filed as #40.

Do you see the arrow on the currently deployed site? I'm concerned this was an earlier regression not related to this PR.

**Comment by sebastianovide** [comment]
neither... It did happened before...

**Comment by steinbro** [comment]
OK, try this branch again.

I think there were at least two bugs I introduced that broke the compass on both iOS and everywhere else. The permissions issue in #40 was due to my turning the active mode setting into a Vue reactive variable and moving this logic into a watch handler instead of leaving it in the click handler where it apparently needs to be.

**Pull request merged**
